import assert from 'node:assert/strict';
import { before, describe, it } from 'node:test';

let compiled;

before(async () => {
  ({ compiled } = await import('../lib/index.js'));
});

describe('transform filter', () => {
  it('transforms plain JavaScript files', async () => {
    const result = await transform(
      "import { css } from '@compiled/react'; export const value = css({ color: 'red' });",
      '/project/src/style.js'
    );

    assertCompiled(result);
  });

  it('transforms plain TypeScript files', async () => {
    const result = await transform(
      "import { css } from '@compiled/react'; export const value: string = css({ color: 'red' });",
      '/project/src/style.ts'
    );

    assertCompiled(result);
  });

  it('strips the query before filtering', async () => {
    const result = await transform(
      "export const Page = () => <div css={{ color: 'red' }} />;",
      '/project/src/style.tsx?direct'
    );

    assertCompiled(result);
    assert.match(result.code, /className=\{ax/);
  });

  it('does not transform dependencies', async () => {
    const result = await transform(
      "// @flow\nopaque type Token = string; export const token: Token = 'dependency';",
      '/project/node_modules/flow-dependency/index.jsx'
    );

    assert.equal(result, undefined);
  });

  it('does not transform plain JavaScript without a Compiled import', async () => {
    const result = await transform(
      "import { jsx } from 'react/jsx-runtime'; export const Page = () => jsx('div', {});",
      '/project/generated/runtime.js'
    );

    assert.equal(result, undefined);
  });
});

async function transform(code, id) {
  const plugin = compiled();
  plugin.configResolved({ root: '/project', resolve: { alias: [] } });
  return plugin.transform.call({}, code, id);
}

function assertCompiled(result) {
  assert.ok(result);
  assert.match(result.code, /generated by @compiled\/babel-plugin/);
}

describe('Vike ?extractAssets modules', () => {
  const code = "export const Page = () => <div css={{ color: 'red' }} />;";

  it('does not add the Compiled import to them', async () => {
    const result = await transform(
      code,
      '/project/src/Page.jsx?extractAssets&lang.jsx'
    );

    assert.match(result.code, /\bcss=\{/);
  });

  it('only recognizes them by the query', async () => {
    const result = await transform(code, '/project/src/extractAssets.jsx');

    assertCompiled(result);
    assert.match(result.code, /className=\{ax\(/);
  });
});
