import assert from 'node:assert/strict';
import { before, describe, it } from 'node:test';

let compiled;

before(async () => {
  ({ compiled } = await import('../lib/index.js'));
});

describe('parser', () => {
  // With the jsx parser plugin enabled, `<string>value` in a .ts file is a syntax error.
  it('parses angle-bracket type assertions in .ts files', async () => {
    const result = await transform(
      `import { css } from '@compiled/react';
const value: unknown = 'red';
export const color = <string>value;
export const styles = css({ color: 'red' });`,
      '/project/src/style.ts'
    );

    assertCompiled(result);
    assert.match(result.code, /<string> ?value/);
  });

  it('parses JSX and types in .tsx files', async () => {
    const result = await transform(
      `import type { ReactNode } from 'react';
export const Page = ({ children }: { children: ReactNode }) => <div css={{ color: 'red' }}>{children}</div>;`,
      '/project/src/Page.tsx'
    );

    assertCompiled(result);
    assert.match(result.code, /className=\{ax\(/);
  });

  it('parses JSX in .jsx files', async () => {
    const result = await transform(
      "export const Page = () => <div css={{ color: 'red' }} />;",
      '/project/src/Page.jsx'
    );

    assertCompiled(result);
    assert.match(result.code, /className=\{ax\(/);
  });

  it('compiles the css prop of every file without a Compiled import', async () => {
    const plugin = setup();
    const code = "export const Page = () => <div css={{ color: 'red' }} />;";
    for (const id of ['/project/src/A.jsx', '/project/src/B.jsx']) {
      const result = await plugin.transform.call({}, code, id);
      assertCompiled(result);
      assert.match(result.code, /className=\{ax\(/);
    }
  });
});

function setup() {
  const plugin = compiled();
  plugin.configResolved({ root: '/project', resolve: { alias: [] } });
  return plugin;
}

async function transform(code, id) {
  return setup().transform.call({}, code, id);
}

function assertCompiled(result) {
  assert.ok(result);
  assert.match(result.code, /generated by @compiled\/babel-plugin/);
}
